#!/bin/bash
#  _                                           
# | |__  ___ _ ____      ___ __ ___  _ __ ___  
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __| 
# | |_) \__ \ |_) \ V  V /| | | | | | | | (__  
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___| 
#           |_|                                
#  
# by Consolider (2024)
# ----------------------------------------------------- 
time=$(date +%H)

# ------------------------------
# AUTOSTART
# ------------------------------
xset r rate 190 33
picom &
wal -i $HOME/.config/wallpaper &
sleep 1
$HOME/.config/polybar/launch.sh &
xset r rate 190 33

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc monitor -d 󰐾 󰐾 󰐾 󰐾 󰐾

## source the colors.
. "${HOME}/.cache/wal/colors.sh"

bspc config border_width         1 #2
bspc config window_gap           3 #6

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color  "$color4"
#bspc config normal_border_color  \#F0C674

#bspc rule -a firefox desktop='^2'
#bspc rule -a Thunar desktop='^3'
#bspc rule -a kdenlive desktop='^5'
#bspc rule -a gimp-2.10 desktop='^7' state=floating follow=on
#bspc rule -a mpv desktop='^15' state=floating
#bspc rule -a mpv monitor='^2' state=floating follow=on rectangle=700x420+1200+600
#bspc rule -a obs desktop='^16' follow=on
bspc rule -a gnome-calculator state=floating
bspc rule -a Nextcloud state=floating
bspc rule -a Imager state=floating
bspc rule -a timeshift-gtk state=floating
bspc rule -a onionshare state=floating
#bspc rule -a scpad state=floating sticky=on rectangle=640x320+250+250
bspc rule -a scpad state=floating sticky=on rectangle=640x320 center=on
## Firefox Picture-in-Picture
#bspc rule -a "*:Toolkit:Picture-in-Picture" monitor='^2' state=floating follow=on rectangle=700x420+1200+600
bspc rule -a "*:Toolkit:Picture-in-Picture" state=floating follow=on rectangle=700x420+1200+600
